import { Timestamp } from 'firebase/firestore';

export type FormFieldType = 
  | 'text' 
  | 'email' 
  | 'number' 
  | 'phone'
  | 'textarea' 
  | 'date' 
  | 'time' 
  | 'datetime'
  | 'select' 
  | 'radio' 
  | 'checkbox'
  | 'file'
  | 'rating'
  | 'slider'
  | 'currency'
  | 'percentage'
  | 'signature'
  | 'location';

export type FormStatus = 'draft' | 'published' | 'archived';
export type FormCategory = 'event' | 'survey' | 'application' | 'update' | 'other';
export type ProgramType = 'leadership-nc' | 'asheville' | 'charlotte' | 'greensboro' | 'statewide' | 'all';

export interface FormFieldValidation {
  min?: number;
  max?: number;
  pattern?: string;
  message?: string;
}

export interface FormField {
  id: string;
  type: FormFieldType;
  label: string;
  placeholder?: string;
  helpText?: string;
  required: boolean;
  validation?: FormFieldValidation;
  options?: string[]; // For select, radio, checkbox
  defaultValue?: any;
  order: number;
}

export interface LCForm {
  id: string;
  title: string;
  description: string;
  fields: FormField[];
  status: FormStatus;
  category: FormCategory;
  tags: string[];
  program: ProgramType;
  qrCodeEnabled: boolean;
  publicUrl: string;
  datasetId?: string;
  userId: string;
  eventDate?: Date;
  registrationDeadline?: Date;
  maxResponses?: number;
  currentResponses?: number;
  allowAnonymous: boolean;
  confirmationMessage?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface FormTemplate {
  id: string;
  name: string;
  description: string;
  category: FormCategory;
  isDefault: boolean;
  schema: {
    title: string;
    description: string;
    sections: FormSection[];
  };
  metadata: {
    tags: string[];
    author: string;
    version: string;
  };
}

export interface FormSection {
  id: string;
  title: string;
  fields: FormField[];
}

export interface FormSubmission {
  id: string;
  formId: string;
  userId?: string;
  data: Record<string, any>;
  submittedAt: Date;
  ipAddress?: string;
  userAgent?: string;
}

export interface Dataset {
  id: string;
  name: string;
  description: string;
  formId: string;
  userId: string;
  format: 'json' | 'csv';
  size: number;
  recordCount: number;
  rowCount: number;
  fields: DatasetField[];
  records: Record<string, any>[];
  metadata: {
    sourceForm: string;
    sourceFormId: string;
    autoGenerated: boolean;
  };
  status: 'active' | 'archived';
  createdAt: Date;
  updatedAt: Date;
}

export interface DatasetField {
  id: string;
  name: string;
  type: string;
  label: string;
}

export interface FormResponse {
  formId: string;
  formTitle: string;
  submittedAt: Date;
  data: Record<string, any>;
}
